package com.bdilab.aiflow.model;

public class GraphType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graph_type.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graph_type.graph_type_name
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private String graphTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graph_type.graph_desc
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private String graphDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graph_type.id
     *
     * @return the value of graph_type.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graph_type.id
     *
     * @param id the value for graph_type.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graph_type.graph_type_name
     *
     * @return the value of graph_type.graph_type_name
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public String getGraphTypeName() {
        return graphTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graph_type.graph_type_name
     *
     * @param graphTypeName the value for graph_type.graph_type_name
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setGraphTypeName(String graphTypeName) {
        this.graphTypeName = graphTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graph_type.graph_desc
     *
     * @return the value of graph_type.graph_desc
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public String getGraphDesc() {
        return graphDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graph_type.graph_desc
     *
     * @param graphDesc the value for graph_type.graph_desc
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setGraphDesc(String graphDesc) {
        this.graphDesc = graphDesc;
    }
}