package com.bdilab.aiflow.model;

public class SystemPresetComponent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_preset_component.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_preset_component.fk_component_info_id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private Integer fkComponentInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_preset_component.type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_preset_component.id
     *
     * @return the value of system_preset_component.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_preset_component.id
     *
     * @param id the value for system_preset_component.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_preset_component.fk_component_info_id
     *
     * @return the value of system_preset_component.fk_component_info_id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public Integer getFkComponentInfoId() {
        return fkComponentInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_preset_component.fk_component_info_id
     *
     * @param fkComponentInfoId the value for system_preset_component.fk_component_info_id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setFkComponentInfoId(Integer fkComponentInfoId) {
        this.fkComponentInfoId = fkComponentInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_preset_component.type
     *
     * @return the value of system_preset_component.type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_preset_component.type
     *
     * @param type the value for system_preset_component.type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }
}