package com.bdilab.aiflow.example;

import java.util.ArrayList;
import java.util.List;

public class ComponentInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public ComponentInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("tags is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("tags is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("tags =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("tags <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("tags >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("tags >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("tags <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("tags <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("tags like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("tags not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("tags in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("tags not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("tags between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("tags not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andIsCustomIsNull() {
            addCriterion("is_custom is null");
            return (Criteria) this;
        }

        public Criteria andIsCustomIsNotNull() {
            addCriterion("is_custom is not null");
            return (Criteria) this;
        }

        public Criteria andIsCustomEqualTo(Byte value) {
            addCriterion("is_custom =", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotEqualTo(Byte value) {
            addCriterion("is_custom <>", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomGreaterThan(Byte value) {
            addCriterion("is_custom >", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_custom >=", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomLessThan(Byte value) {
            addCriterion("is_custom <", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomLessThanOrEqualTo(Byte value) {
            addCriterion("is_custom <=", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomIn(List<Byte> values) {
            addCriterion("is_custom in", values, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotIn(List<Byte> values) {
            addCriterion("is_custom not in", values, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomBetween(Byte value1, Byte value2) {
            addCriterion("is_custom between", value1, value2, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotBetween(Byte value1, Byte value2) {
            addCriterion("is_custom not between", value1, value2, "isCustom");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrIsNull() {
            addCriterion("component_yaml_addr is null");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrIsNotNull() {
            addCriterion("component_yaml_addr is not null");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrEqualTo(String value) {
            addCriterion("component_yaml_addr =", value, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrNotEqualTo(String value) {
            addCriterion("component_yaml_addr <>", value, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrGreaterThan(String value) {
            addCriterion("component_yaml_addr >", value, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrGreaterThanOrEqualTo(String value) {
            addCriterion("component_yaml_addr >=", value, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrLessThan(String value) {
            addCriterion("component_yaml_addr <", value, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrLessThanOrEqualTo(String value) {
            addCriterion("component_yaml_addr <=", value, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrLike(String value) {
            addCriterion("component_yaml_addr like", value, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrNotLike(String value) {
            addCriterion("component_yaml_addr not like", value, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrIn(List<String> values) {
            addCriterion("component_yaml_addr in", values, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrNotIn(List<String> values) {
            addCriterion("component_yaml_addr not in", values, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrBetween(String value1, String value2) {
            addCriterion("component_yaml_addr between", value1, value2, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andComponentYamlAddrNotBetween(String value1, String value2) {
            addCriterion("component_yaml_addr not between", value1, value2, "componentYamlAddr");
            return (Criteria) this;
        }

        public Criteria andInputStubIsNull() {
            addCriterion("input_stub is null");
            return (Criteria) this;
        }

        public Criteria andInputStubIsNotNull() {
            addCriterion("input_stub is not null");
            return (Criteria) this;
        }

        public Criteria andInputStubEqualTo(String value) {
            addCriterion("input_stub =", value, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubNotEqualTo(String value) {
            addCriterion("input_stub <>", value, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubGreaterThan(String value) {
            addCriterion("input_stub >", value, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubGreaterThanOrEqualTo(String value) {
            addCriterion("input_stub >=", value, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubLessThan(String value) {
            addCriterion("input_stub <", value, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubLessThanOrEqualTo(String value) {
            addCriterion("input_stub <=", value, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubLike(String value) {
            addCriterion("input_stub like", value, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubNotLike(String value) {
            addCriterion("input_stub not like", value, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubIn(List<String> values) {
            addCriterion("input_stub in", values, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubNotIn(List<String> values) {
            addCriterion("input_stub not in", values, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubBetween(String value1, String value2) {
            addCriterion("input_stub between", value1, value2, "inputStub");
            return (Criteria) this;
        }

        public Criteria andInputStubNotBetween(String value1, String value2) {
            addCriterion("input_stub not between", value1, value2, "inputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubIsNull() {
            addCriterion("output_stub is null");
            return (Criteria) this;
        }

        public Criteria andOutputStubIsNotNull() {
            addCriterion("output_stub is not null");
            return (Criteria) this;
        }

        public Criteria andOutputStubEqualTo(String value) {
            addCriterion("output_stub =", value, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubNotEqualTo(String value) {
            addCriterion("output_stub <>", value, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubGreaterThan(String value) {
            addCriterion("output_stub >", value, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubGreaterThanOrEqualTo(String value) {
            addCriterion("output_stub >=", value, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubLessThan(String value) {
            addCriterion("output_stub <", value, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubLessThanOrEqualTo(String value) {
            addCriterion("output_stub <=", value, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubLike(String value) {
            addCriterion("output_stub like", value, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubNotLike(String value) {
            addCriterion("output_stub not like", value, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubIn(List<String> values) {
            addCriterion("output_stub in", values, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubNotIn(List<String> values) {
            addCriterion("output_stub not in", values, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubBetween(String value1, String value2) {
            addCriterion("output_stub between", value1, value2, "outputStub");
            return (Criteria) this;
        }

        public Criteria andOutputStubNotBetween(String value1, String value2) {
            addCriterion("output_stub not between", value1, value2, "outputStub");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsIsNull() {
            addCriterion("graph_type_ids is null");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsIsNotNull() {
            addCriterion("graph_type_ids is not null");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsEqualTo(Integer value) {
            addCriterion("graph_type_ids =", value, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsNotEqualTo(Integer value) {
            addCriterion("graph_type_ids <>", value, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsGreaterThan(Integer value) {
            addCriterion("graph_type_ids >", value, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsGreaterThanOrEqualTo(Integer value) {
            addCriterion("graph_type_ids >=", value, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsLessThan(Integer value) {
            addCriterion("graph_type_ids <", value, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsLessThanOrEqualTo(Integer value) {
            addCriterion("graph_type_ids <=", value, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsIn(List<Integer> values) {
            addCriterion("graph_type_ids in", values, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsNotIn(List<Integer> values) {
            addCriterion("graph_type_ids not in", values, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsBetween(Integer value1, Integer value2) {
            addCriterion("graph_type_ids between", value1, value2, "graphTypeIds");
            return (Criteria) this;
        }

        public Criteria andGraphTypeIdsNotBetween(Integer value1, Integer value2) {
            addCriterion("graph_type_ids not between", value1, value2, "graphTypeIds");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table component_info
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 31 13:47:58 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table component_info
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}