package com.bdilab.aiflow.mapper;

import com.bdilab.aiflow.model.GraphType;

import java.util.List;

public interface GraphTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int insert(GraphType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    GraphType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    List<GraphType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int updateByPrimaryKey(GraphType record);
}