package com.bdilab.aiflow.mapper;

import com.bdilab.aiflow.model.SystemPresetComponent;

import java.util.List;

public interface SystemPresetComponentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_preset_component
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_preset_component
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int insert(SystemPresetComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_preset_component
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    SystemPresetComponent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_preset_component
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    List<SystemPresetComponent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_preset_component
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int updateByPrimaryKey(SystemPresetComponent record);
}