package com.bdilab.aiflow.mapper;

import com.bdilab.aiflow.model.ComponentOutputStub;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComponentOutputStubMapper {
//    /**
//     * 删除一个实验运行下的所有组件输出
//     * @param runningId
//     * @return
//     */
//    int deleteByRunningId(Integer runningId);

    /**
     * 通过运行id组件id和图类型
     * @param runningId
     * @param fkComponentInfoId
     * @param graphType
     * @return
     */
    List<ComponentOutputStub> selectByRunningComponentAndType(@Param("runningId") Integer runningId,
                                                              @Param("fkComponentInfoId") Integer fkComponentInfoId,
                                                              @Param("graphtype") Integer graphType);
    /**
     * 通过运行id和组件id
     * @param runningId
     * @param fkComponentInfoId
     * @return
     */
    List<ComponentOutputStub> selectByRunningId(@Param("runningId") Integer runningId, @Param("fkComponentInfoId") Integer fkComponentInfoId);

    /**
     * 通过组件输出id删除组件输出
     * @param outputId
     * @return
     */
    boolean deleteOutputById(Integer outputId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_output_stub
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_output_stub
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int insert(ComponentOutputStub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_output_stub
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    ComponentOutputStub selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_output_stub
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    List<ComponentOutputStub> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_output_stub
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    int updateByPrimaryKey(ComponentOutputStub record);
    ComponentOutputStub selectById(Integer id);

}