package com.bdilab.aiflow.mapper;

import com.bdilab.aiflow.model.WorkflowComponent;

public interface WorkflowComponentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_component
     *
     * @mbg.generated Tue Dec 08 10:30:56 CST 2020
     */
    int insert(WorkflowComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow_component
     *
     * @mbg.generated Tue Dec 08 10:30:56 CST 2020
     */
    int insertSelective(WorkflowComponent record);
}