package com.bdilab.aiflow.example;

import java.util.ArrayList;
import java.util.List;

public class GraphTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public GraphTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameIsNull() {
            addCriterion("graph_type_name is null");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameIsNotNull() {
            addCriterion("graph_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameEqualTo(String value) {
            addCriterion("graph_type_name =", value, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameNotEqualTo(String value) {
            addCriterion("graph_type_name <>", value, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameGreaterThan(String value) {
            addCriterion("graph_type_name >", value, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("graph_type_name >=", value, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameLessThan(String value) {
            addCriterion("graph_type_name <", value, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameLessThanOrEqualTo(String value) {
            addCriterion("graph_type_name <=", value, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameLike(String value) {
            addCriterion("graph_type_name like", value, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameNotLike(String value) {
            addCriterion("graph_type_name not like", value, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameIn(List<String> values) {
            addCriterion("graph_type_name in", values, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameNotIn(List<String> values) {
            addCriterion("graph_type_name not in", values, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameBetween(String value1, String value2) {
            addCriterion("graph_type_name between", value1, value2, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphTypeNameNotBetween(String value1, String value2) {
            addCriterion("graph_type_name not between", value1, value2, "graphTypeName");
            return (Criteria) this;
        }

        public Criteria andGraphDescIsNull() {
            addCriterion("graph_desc is null");
            return (Criteria) this;
        }

        public Criteria andGraphDescIsNotNull() {
            addCriterion("graph_desc is not null");
            return (Criteria) this;
        }

        public Criteria andGraphDescEqualTo(String value) {
            addCriterion("graph_desc =", value, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescNotEqualTo(String value) {
            addCriterion("graph_desc <>", value, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescGreaterThan(String value) {
            addCriterion("graph_desc >", value, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescGreaterThanOrEqualTo(String value) {
            addCriterion("graph_desc >=", value, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescLessThan(String value) {
            addCriterion("graph_desc <", value, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescLessThanOrEqualTo(String value) {
            addCriterion("graph_desc <=", value, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescLike(String value) {
            addCriterion("graph_desc like", value, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescNotLike(String value) {
            addCriterion("graph_desc not like", value, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescIn(List<String> values) {
            addCriterion("graph_desc in", values, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescNotIn(List<String> values) {
            addCriterion("graph_desc not in", values, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescBetween(String value1, String value2) {
            addCriterion("graph_desc between", value1, value2, "graphDesc");
            return (Criteria) this;
        }

        public Criteria andGraphDescNotBetween(String value1, String value2) {
            addCriterion("graph_desc not between", value1, value2, "graphDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graph_type
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 31 13:47:58 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graph_type
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}