package com.bdilab.aiflow.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WorkflowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public WorkflowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andFkUserIdIsNull() {
            addCriterion("fk_user_id is null");
            return (Criteria) this;
        }

        public Criteria andFkUserIdIsNotNull() {
            addCriterion("fk_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andFkUserIdEqualTo(Integer value) {
            addCriterion("fk_user_id =", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdNotEqualTo(Integer value) {
            addCriterion("fk_user_id <>", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdGreaterThan(Integer value) {
            addCriterion("fk_user_id >", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fk_user_id >=", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdLessThan(Integer value) {
            addCriterion("fk_user_id <", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("fk_user_id <=", value, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdIn(List<Integer> values) {
            addCriterion("fk_user_id in", values, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdNotIn(List<Integer> values) {
            addCriterion("fk_user_id not in", values, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdBetween(Integer value1, Integer value2) {
            addCriterion("fk_user_id between", value1, value2, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andFkUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fk_user_id not between", value1, value2, "fkUserId");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("tags is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("tags is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("tags =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("tags <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("tags >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("tags >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("tags <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("tags <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("tags like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("tags not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("tags in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("tags not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("tags between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("tags not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Byte value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Byte value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Byte value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Byte value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Byte> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Byte> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Byte value1, Byte value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrIsNull() {
            addCriterion("workflow_xml_addr is null");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrIsNotNull() {
            addCriterion("workflow_xml_addr is not null");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrEqualTo(String value) {
            addCriterion("workflow_xml_addr =", value, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrNotEqualTo(String value) {
            addCriterion("workflow_xml_addr <>", value, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrGreaterThan(String value) {
            addCriterion("workflow_xml_addr >", value, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrGreaterThanOrEqualTo(String value) {
            addCriterion("workflow_xml_addr >=", value, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrLessThan(String value) {
            addCriterion("workflow_xml_addr <", value, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrLessThanOrEqualTo(String value) {
            addCriterion("workflow_xml_addr <=", value, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrLike(String value) {
            addCriterion("workflow_xml_addr like", value, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrNotLike(String value) {
            addCriterion("workflow_xml_addr not like", value, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrIn(List<String> values) {
            addCriterion("workflow_xml_addr in", values, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrNotIn(List<String> values) {
            addCriterion("workflow_xml_addr not in", values, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrBetween(String value1, String value2) {
            addCriterion("workflow_xml_addr between", value1, value2, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andWorkflowXmlAddrNotBetween(String value1, String value2) {
            addCriterion("workflow_xml_addr not between", value1, value2, "workflowXmlAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrIsNull() {
            addCriterion("generate_pipeline_addr is null");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrIsNotNull() {
            addCriterion("generate_pipeline_addr is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrEqualTo(String value) {
            addCriterion("generate_pipeline_addr =", value, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrNotEqualTo(String value) {
            addCriterion("generate_pipeline_addr <>", value, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrGreaterThan(String value) {
            addCriterion("generate_pipeline_addr >", value, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrGreaterThanOrEqualTo(String value) {
            addCriterion("generate_pipeline_addr >=", value, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrLessThan(String value) {
            addCriterion("generate_pipeline_addr <", value, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrLessThanOrEqualTo(String value) {
            addCriterion("generate_pipeline_addr <=", value, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrLike(String value) {
            addCriterion("generate_pipeline_addr like", value, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrNotLike(String value) {
            addCriterion("generate_pipeline_addr not like", value, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrIn(List<String> values) {
            addCriterion("generate_pipeline_addr in", values, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrNotIn(List<String> values) {
            addCriterion("generate_pipeline_addr not in", values, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrBetween(String value1, String value2) {
            addCriterion("generate_pipeline_addr between", value1, value2, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andGeneratePipelineAddrNotBetween(String value1, String value2) {
            addCriterion("generate_pipeline_addr not between", value1, value2, "generatePipelineAddr");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsIsNull() {
            addCriterion("fk_custom_component_ids is null");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsIsNotNull() {
            addCriterion("fk_custom_component_ids is not null");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsEqualTo(String value) {
            addCriterion("fk_custom_component_ids =", value, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsNotEqualTo(String value) {
            addCriterion("fk_custom_component_ids <>", value, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsGreaterThan(String value) {
            addCriterion("fk_custom_component_ids >", value, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsGreaterThanOrEqualTo(String value) {
            addCriterion("fk_custom_component_ids >=", value, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsLessThan(String value) {
            addCriterion("fk_custom_component_ids <", value, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsLessThanOrEqualTo(String value) {
            addCriterion("fk_custom_component_ids <=", value, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsLike(String value) {
            addCriterion("fk_custom_component_ids like", value, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsNotLike(String value) {
            addCriterion("fk_custom_component_ids not like", value, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsIn(List<String> values) {
            addCriterion("fk_custom_component_ids in", values, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsNotIn(List<String> values) {
            addCriterion("fk_custom_component_ids not in", values, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsBetween(String value1, String value2) {
            addCriterion("fk_custom_component_ids between", value1, value2, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andFkCustomComponentIdsNotBetween(String value1, String value2) {
            addCriterion("fk_custom_component_ids not between", value1, value2, "fkCustomComponentIds");
            return (Criteria) this;
        }

        public Criteria andIsCustomIsNull() {
            addCriterion("is_custom is null");
            return (Criteria) this;
        }

        public Criteria andIsCustomIsNotNull() {
            addCriterion("is_custom is not null");
            return (Criteria) this;
        }

        public Criteria andIsCustomEqualTo(Byte value) {
            addCriterion("is_custom =", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotEqualTo(Byte value) {
            addCriterion("is_custom <>", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomGreaterThan(Byte value) {
            addCriterion("is_custom >", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_custom >=", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomLessThan(Byte value) {
            addCriterion("is_custom <", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomLessThanOrEqualTo(Byte value) {
            addCriterion("is_custom <=", value, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomIn(List<Byte> values) {
            addCriterion("is_custom in", values, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotIn(List<Byte> values) {
            addCriterion("is_custom not in", values, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomBetween(Byte value1, Byte value2) {
            addCriterion("is_custom between", value1, value2, "isCustom");
            return (Criteria) this;
        }

        public Criteria andIsCustomNotBetween(Byte value1, Byte value2) {
            addCriterion("is_custom not between", value1, value2, "isCustom");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table workflow
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 31 13:47:58 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table workflow
     *
     * @mbg.generated Mon Aug 31 13:47:58 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}