package com.bdilab.aiflow.model;

import lombok.Data;

@Data
public class ComponentParameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_parameter.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_parameter.name
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_parameter.fk_component_info_id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private Integer fkComponentInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_parameter.parameter_type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private String parameterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_parameter.default_value
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private String defaultValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_parameter.parameter_desc
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    private String parameterDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_parameter.id
     *
     * @return the value of component_parameter.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_parameter.id
     *
     * @param id the value for component_parameter.id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_parameter.name
     *
     * @return the value of component_parameter.name
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_parameter.name
     *
     * @param name the value for component_parameter.name
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_parameter.fk_component_info_id
     *
     * @return the value of component_parameter.fk_component_info_id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public Integer getFkComponentInfoId() {
        return fkComponentInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_parameter.fk_component_info_id
     *
     * @param fkComponentInfoId the value for component_parameter.fk_component_info_id
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setFkComponentInfoId(Integer fkComponentInfoId) {
        this.fkComponentInfoId = fkComponentInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_parameter.parameter_type
     *
     * @return the value of component_parameter.parameter_type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public String getParameterType() {
        return parameterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_parameter.parameter_type
     *
     * @param parameterType the value for component_parameter.parameter_type
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setParameterType(String parameterType) {
        this.parameterType = parameterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_parameter.default_value
     *
     * @return the value of component_parameter.default_value
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_parameter.default_value
     *
     * @param defaultValue the value for component_parameter.default_value
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_parameter.parameter_desc
     *
     * @return the value of component_parameter.parameter_desc
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public String getParameterDesc() {
        return parameterDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_parameter.parameter_desc
     *
     * @param parameterDesc the value for component_parameter.parameter_desc
     *
     * @mbg.generated Sun Aug 30 16:18:08 CST 2020
     */
    public void setParameterDesc(String parameterDesc) {
        this.parameterDesc = parameterDesc;
    }
}