package com.bdilab.aiflow.model;

public class ComponentOutputStub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_output_stub.id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_output_stub.fk_component_info_id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    private Integer fkComponentInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_output_stub.fk_running_id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    private Integer fkRunningId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_output_stub.output_file_type
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    private String outputFileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_output_stub.output_table_name
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    private String outputTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_output_stub.output_file_addr
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    private String outputFileAddr;

    private Integer graphType;


    public Integer getGraphType() {
        return graphType;
    }

    public void setGraphType(Integer graphType) {
        this.graphType = graphType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_output_stub.id
     *
     * @return the value of component_output_stub.id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_output_stub.id
     *
     * @param id the value for component_output_stub.id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_output_stub.fk_component_info_id
     *
     * @return the value of component_output_stub.fk_component_info_id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public Integer getFkComponentInfoId() {
        return fkComponentInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_output_stub.fk_component_info_id
     *
     * @param fkComponentInfoId the value for component_output_stub.fk_component_info_id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public void setFkComponentInfoId(Integer fkComponentInfoId) {
        this.fkComponentInfoId = fkComponentInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_output_stub.fk_running_id
     *
     * @return the value of component_output_stub.fk_running_id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public Integer getFkRunningId() {
        return fkRunningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_output_stub.fk_running_id
     *
     * @param fkRunningId the value for component_output_stub.fk_running_id
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public void setFkRunningId(Integer fkRunningId) {
        this.fkRunningId = fkRunningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_output_stub.output_file_type
     *
     * @return the value of component_output_stub.output_file_type
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public String getOutputFileType() {
        return outputFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_output_stub.output_file_type
     *
     * @param outputFileType the value for component_output_stub.output_file_type
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public void setOutputFileType(String outputFileType) {
        this.outputFileType = outputFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_output_stub.output_table_name
     *
     * @return the value of component_output_stub.output_table_name
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public String getOutputTableName() {
        return outputTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_output_stub.output_table_name
     *
     * @param outputTableName the value for component_output_stub.output_table_name
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public void setOutputTableName(String outputTableName) {
        this.outputTableName = outputTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_output_stub.output_file_addr
     *
     * @return the value of component_output_stub.output_file_addr
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public String getOutputFileAddr() {
        return outputFileAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_output_stub.output_file_addr
     *
     * @param outputFileAddr the value for component_output_stub.output_file_addr
     *
     * @mbggenerated Mon Aug 31 20:21:37 CST 2020
     */
    public void setOutputFileAddr(String outputFileAddr) {
        this.outputFileAddr = outputFileAddr;
    }
}