package com.bdilab.aiflow.model;

public class EnumValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_value.id
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_value.fk_python_func_variable_id
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */
    private Integer fkComponentVariableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_value.value
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */
    private String value;

    private String enumDes;

    public String getEnumDes() {
        return enumDes;
    }

    public void setEnumDes(String enumDes) {
        this.enumDes = enumDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_value.id
     *
     * @return the value of enum_value.id
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enum_value.id
     *
     * @param id the value for enum_value.id
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_value.fk_python_func_variable_id
     *
     * @return the value of enum_value.fk_python_func_variable_id
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */
    public Integer getFkComponentVariableId() {
        return fkComponentVariableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enum_value.fk_python_func_variable_id
     *
     * @param fkComponentVariableId the value for enum_value.fk_python_func_variable_id
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */
    public void setFkComponentVariableId(Integer fkComponentVariableId) {
        this.fkComponentVariableId = fkComponentVariableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_value.value
     *
     * @return the value of enum_value.value
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enum_value.value
     *
     * @param value the value for enum_value.value
     *
     * @mbg.generated Tue Oct 15 10:27:29 CST 2019
     */
    public void setValue(String value) {
        this.value = value;
    }
}