package com.bdilab.aiflow.model;

import java.util.Date;

public class ExperimentRunning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_running.id
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    private Integer id;
    private Integer fkUserId;
    private String fkDlResultTableName;
    private String conversationId;

    public String getFkDlResultTableName() {
        return fkDlResultTableName;
    }

    public void setFkDlResultTableName(String fkDlResultTableName) {
        this.fkDlResultTableName = fkDlResultTableName;
    }

    public Integer getFkModelId() {
        return fkModelId;
    }

    public void setFkModelId(Integer fkModelId) {
        this.fkModelId = fkModelId;
    }

    private Integer fkModelId;

    public Integer getFkUserId() {
        return fkUserId;
    }

    public void setFkUserId(Integer fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_running.running_status
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    private Integer runningStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_running.is_deleted
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_running.fk_experiment_id
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    private Integer fkExperimentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_running.start_time
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experiment_running.end_time
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    private Date endTime;

    private String runId;

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_running.id
     *
     * @return the value of experiment_running.id
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_running.id
     *
     * @param id the value for experiment_running.id
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_running.running_status
     *
     * @return the value of experiment_running.running_status
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public Integer getRunningStatus() {
        return runningStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_running.running_status
     *
     * @param runningStatus the value for experiment_running.running_status
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public void setRunningStatus(Integer runningStatus) {
        this.runningStatus = runningStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_running.is_deleted
     *
     * @return the value of experiment_running.is_deleted
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_running.is_deleted
     *
     * @param isDeleted the value for experiment_running.is_deleted
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_running.fk_experiment_id
     *
     * @return the value of experiment_running.fk_experiment_id
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public Integer getFkExperimentId() {
        return fkExperimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_running.fk_experiment_id
     *
     * @param fkExperimentId the value for experiment_running.fk_experiment_id
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public void setFkExperimentId(Integer fkExperimentId) {
        this.fkExperimentId = fkExperimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_running.start_time
     *
     * @return the value of experiment_running.start_time
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_running.start_time
     *
     * @param startTime the value for experiment_running.start_time
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experiment_running.end_time
     *
     * @return the value of experiment_running.end_time
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experiment_running.end_time
     *
     * @param endTime the value for experiment_running.end_time
     *
     * @mbggenerated Wed Sep 02 10:16:42 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getRunId() {
        return runId;
    }

    public void setRunId(String runId) {
        this.runId = runId;
    }
}