package com.bdilab.aiflow.model;

import java.util.Date;

public class Workflow {

    private Integer id;

    private String name;

    private Integer fkUserId;

    private String tags;

    private Byte isDeleted;

    private String workflowXmlAddr;

    private String ggeditorObjectString;

    private String generatePipelineAddr;

    private String pipelineYamlAddr;

    private String pipelineId;

    private String fkCustomComponentIds;

    private Byte isCustom;

    private Date createTime;

    private String workflowDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.id
     *
     * @return the value of workflow.id
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.id
     *
     * @param id the value for workflow.id
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.name
     *
     * @return the value of workflow.name
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.name
     *
     * @param name the value for workflow.name
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.fk_user_id
     *
     * @return the value of workflow.fk_user_id
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public Integer getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.fk_user_id
     *
     * @param fkUserId the value for workflow.fk_user_id
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setFkUserId(Integer fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.tags
     *
     * @return the value of workflow.tags
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.tags
     *
     * @param tags the value for workflow.tags
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.is_deleted
     *
     * @return the value of workflow.is_deleted
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.is_deleted
     *
     * @param isDeleted the value for workflow.is_deleted
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.workflow_xml_addr
     *
     * @return the value of workflow.workflow_xml_addr
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public String getWorkflowXmlAddr() {
        return workflowXmlAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.workflow_xml_addr
     *
     * @param workflowXmlAddr the value for workflow.workflow_xml_addr
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setWorkflowXmlAddr(String workflowXmlAddr) {
        this.workflowXmlAddr = workflowXmlAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.ggeditor_object_string
     *
     * @return the value of workflow.ggeditor_object_string
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public String getGgeditorObjectString() {
        return ggeditorObjectString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.ggeditor_object_string
     *
     * @param ggeditorObjectString the value for workflow.ggeditor_object_string
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setGgeditorObjectString(String ggeditorObjectString) {
        this.ggeditorObjectString = ggeditorObjectString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.generate_pipeline_addr
     *
     * @return the value of workflow.generate_pipeline_addr
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public String getGeneratePipelineAddr() {
        return generatePipelineAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.generate_pipeline_addr
     *
     * @param generatePipelineAddr the value for workflow.generate_pipeline_addr
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setGeneratePipelineAddr(String generatePipelineAddr) {
        this.generatePipelineAddr = generatePipelineAddr;
    }

    public String getPipelineYamlAddr() {
        return pipelineYamlAddr;
    }

    public void setPipelineYamlAddr(String pipelineYamlAddr) {
        this.pipelineYamlAddr = pipelineYamlAddr;
    }

    public String getPipelineId() {
        return pipelineId;
    }

    public void setPipelineId(String pipelineId) {
        this.pipelineId = pipelineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.fk_custom_component_ids
     *
     * @return the value of workflow.fk_custom_component_ids
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public String getFkCustomComponentIds() {
        return fkCustomComponentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.fk_custom_component_ids
     *
     * @param fkCustomComponentIds the value for workflow.fk_custom_component_ids
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setFkCustomComponentIds(String fkCustomComponentIds) {
        this.fkCustomComponentIds = fkCustomComponentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.is_custom
     *
     * @return the value of workflow.is_custom
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public Byte getIsCustom() {
        return isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.is_custom
     *
     * @param isCustom the value for workflow.is_custom
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setIsCustom(Byte isCustom) {
        this.isCustom = isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.create_time
     *
     * @return the value of workflow.create_time
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.create_time
     *
     * @param createTime the value for workflow.create_time
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow.workflow_desc
     *
     * @return the value of workflow.workflow_desc
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public String getWorkflowDesc() {
        return workflowDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow.workflow_desc
     *
     * @param workflowDesc the value for workflow.workflow_desc
     *
     * @mbg.generated Tue Sep 01 22:46:06 CST 2020
     */
    public void setWorkflowDesc(String workflowDesc) {
        this.workflowDesc = workflowDesc;
    }
}