package com.bdilab.aiflow.model;

import java.util.Date;

public class WorkflowComponent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_component.id
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_component.name
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_component.tag
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_component.workflow_component_desc
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    private String workflowComponentDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_component.is_deleted
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_component.create_time
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_component.fk_user_id
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    private Integer fkUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_component.ggeditor_object_string
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    private String ggeditorObjectString;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_component.id
     *
     * @return the value of workflow_component.id
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_component.id
     *
     * @param id the value for workflow_component.id
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_component.name
     *
     * @return the value of workflow_component.name
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_component.name
     *
     * @param name the value for workflow_component.name
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_component.tag
     *
     * @return the value of workflow_component.tag
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_component.tag
     *
     * @param tag the value for workflow_component.tag
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_component.workflow_component_desc
     *
     * @return the value of workflow_component.workflow_component_desc
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public String getWorkflowComponentDesc() {
        return workflowComponentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_component.workflow_component_desc
     *
     * @param workflowComponentDesc the value for workflow_component.workflow_component_desc
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public void setWorkflowComponentDesc(String workflowComponentDesc) {
        this.workflowComponentDesc = workflowComponentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_component.is_deleted
     *
     * @return the value of workflow_component.is_deleted
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_component.is_deleted
     *
     * @param isDeleted the value for workflow_component.is_deleted
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_component.create_time
     *
     * @return the value of workflow_component.create_time
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_component.create_time
     *
     * @param createTime the value for workflow_component.create_time
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_component.fk_user_id
     *
     * @return the value of workflow_component.fk_user_id
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public Integer getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_component.fk_user_id
     *
     * @param fkUserId the value for workflow_component.fk_user_id
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public void setFkUserId(Integer fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_component.ggeditor_object_string
     *
     * @return the value of workflow_component.ggeditor_object_string
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public String getGgeditorObjectString() {
        return ggeditorObjectString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_component.ggeditor_object_string
     *
     * @param ggeditorObjectString the value for workflow_component.ggeditor_object_string
     *
     * @mbg.generated Tue Dec 08 11:06:52 CST 2020
     */
    public void setGgeditorObjectString(String ggeditorObjectString) {
        this.ggeditorObjectString = ggeditorObjectString;
    }
}